import { Jersey_15 } from 'next/font/google';
import "./globals.css";
import Nav from "./components/Nav"

const jersey15 = Jersey_15({
  subsets: ['latin'],
  weight: ['400', '400'], // whatever weights you need
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jersey15.className}>
      <body>
         <Nav/>
        {children}
       
      </body>
    </html>
  );
}
